[package]
name = "sum_type"
version = "0.1.0"
authors = ["Michael Bryan <michaelfbryan@gmail.com>"]

[dependencies]

[features]
default = []
try_from = []
generated_example = []

[package.metadata.docs.rs]
all-features = true
